In [1]:
#Exercise 1: Create a 1D NumPy array containing numbers from 0 to 9.

import numpy as np

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # Creating a 1D NumPy array

array_1d2 = np.arange(1, 10) #testing the range alternative so I don't have to type it in the future

print("1D Array:", array_1d)

print("1D Array - Range Method:", array_1d2)




1D Array: [1 2 3 4 5 6 7 8 9]
1D Array - Range Method: [1 2 3 4 5 6 7 8 9]


In [13]:
#Exercise 2: Type Conversion and Array Operations

this_list = [3.14, 2.17, 0, 1, 2]
now_array = np.array(this_list) #Converts list into a NumPy array

# printing the type of my_array
print(now_array.dtype)

intarray = now_array.astype(int) #convert data type to integer

print(intarray.dtype)



float64
int64


In [16]:
#Exercise 3: Working with Multi-Dimensional Arrays
array_3d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Create a 3x3 NumPy array with values ranging from 1 to 9.
print("3D Array:", array_3d)

3D Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
#Exercise 4: Create a 2D NumPy array of shape (4, 5) filled with random numbers.

np.set_printoptions(suppress=True, precision=2)  #changed to reduce the size

randomizer = np.random.random((4,5))

print(randomizer)


[[0.03 0.36 0.4  0.38 0.28]
 [0.58 0.09 0.61 0.6  0.08]
 [0.98 0.49 0.46 0.36 0.49]
 [0.18 0.35 0.29 0.02 0.7 ]]


In [21]:
#Exercise 5 : Indexing Arrays

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

print(array)


access_array = array[[1]] #access the second row of the array
print("\nAccessed Rows :")
print(access_array)

[[21 22 23 22 22]
 [20 21 22 23 24]
 [21 22 23 22 22]]

Accessed Rows :
[[20 21 22 23 24]]


In [26]:
#Exercise 6 : Reversing elements order in a given 1D NumPy array (first element becomes last).

original = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

reversed_arr = original[::-1] #reversed elements
print(reversed_arr) #first is now last


[0 1 2 3 4 5 6 7 8 9]


In [27]:
#Exercise 7: Create a 4x4 identity matrix using NumPy.

imatrix = np.identity(4) #4x4 creation
print(imatrix) #meets expected output

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
#Exercise 8: Find the sum and average of a given 1D array

array_1d = np.array([0,1,2,3,4,5,6,7,8,9]) #the exercise didn't give me the array!!

print(f"Sum: {np.sum(array_1d)} and Average: {np.mean(array_1d)}")

Sum: 45 and Average: 4.5


In [32]:
#Exercise 9: Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

array_1d = np.arange(1, 21) #created the array
print(array_1d)

reshaping = array_1d.reshape(4, 5)
print(reshaping) #should be a 4x5 matrix



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [34]:
#Exercise 10: Extract all odd numbers from a given NumPy array.

original = np.array([0,1,2,3,4,5,6,7,8,9])

updated_array = original[original % 2 == 1]

print(updated_array)

[1 3 5 7 9]
